// Generated by scripts/generate-responsive-images.mjs. Do not edit by hand.
export type ResponsiveImageVariant = {
  width: number;
  src: string;
  bytes: number;
};

export type ResponsiveImageEntry = {
  width: number;
  height: number;
  originalBytes: number;
  variants: ResponsiveImageVariant[];
};

export const responsiveImageManifest = {
  "ad-creative-1": {
    "width": 900,
    "height": 900,
    "originalBytes": 140857,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-1-320.webp",
        "bytes": 9884
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-1-640.webp",
        "bytes": 21150
      }
    ]
  },
  "ad-creative-2": {
    "width": 900,
    "height": 900,
    "originalBytes": 156943,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-2-320.webp",
        "bytes": 9350
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-2-640.webp",
        "bytes": 22694
      }
    ]
  },
  "ad-creative-3": {
    "width": 900,
    "height": 900,
    "originalBytes": 197647,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-3-320.webp",
        "bytes": 11280
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-3-640.webp",
        "bytes": 28520
      }
    ]
  },
  "ad-creative-4": {
    "width": 506,
    "height": 900,
    "originalBytes": 108665,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-4-320.webp",
        "bytes": 16140
      }
    ]
  },
  "cm-clarrio-1": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 406369,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-clarrio-1-320.webp",
        "bytes": 10252
      },
      {
        "width": 640,
        "src": "/responsive/cm-clarrio-1-640.webp",
        "bytes": 24820
      },
      {
        "width": 1024,
        "src": "/responsive/cm-clarrio-1-1024.webp",
        "bytes": 60730
      }
    ]
  },
  "cm-clarrio-2": {
    "width": 1400,
    "height": 933,
    "originalBytes": 482393,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-clarrio-2-320.webp",
        "bytes": 6256
      },
      {
        "width": 640,
        "src": "/responsive/cm-clarrio-2-640.webp",
        "bytes": 14954
      },
      {
        "width": 1024,
        "src": "/responsive/cm-clarrio-2-1024.webp",
        "bytes": 29838
      }
    ]
  },
  "cm-foodcost": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1038505,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-foodcost-320.webp",
        "bytes": 7030
      },
      {
        "width": 640,
        "src": "/responsive/cm-foodcost-640.webp",
        "bytes": 17540
      },
      {
        "width": 1024,
        "src": "/responsive/cm-foodcost-1024.webp",
        "bytes": 30534
      }
    ]
  },
  "cm-pubrella-1": {
    "width": 1024,
    "height": 1536,
    "originalBytes": 770884,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-pubrella-1-320.webp",
        "bytes": 15640
      },
      {
        "width": 640,
        "src": "/responsive/cm-pubrella-1-640.webp",
        "bytes": 46918
      },
      {
        "width": 1024,
        "src": "/responsive/cm-pubrella-1-1024.webp",
        "bytes": 118390
      }
    ]
  },
  "cm-pubrella-2": {
    "width": 1024,
    "height": 1536,
    "originalBytes": 819839,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-pubrella-2-320.webp",
        "bytes": 14666
      },
      {
        "width": 640,
        "src": "/responsive/cm-pubrella-2-640.webp",
        "bytes": 34454
      },
      {
        "width": 1024,
        "src": "/responsive/cm-pubrella-2-1024.webp",
        "bytes": 64720
      }
    ]
  },
  "cm-shipzzer-collage": {
    "width": 1920,
    "height": 886,
    "originalBytes": 616747,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-collage-320.webp",
        "bytes": 9408
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-collage-640.webp",
        "bytes": 26880
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-collage-1024.webp",
        "bytes": 53374
      }
    ]
  },
  "cm-shipzzer-invoices": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1128632,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-invoices-320.webp",
        "bytes": 9666
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-invoices-640.webp",
        "bytes": 21322
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-invoices-1024.webp",
        "bytes": 39112
      }
    ]
  },
  "cm-shipzzer-repair": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1242929,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-repair-320.webp",
        "bytes": 10308
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-repair-640.webp",
        "bytes": 24680
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-repair-1024.webp",
        "bytes": 44160
      }
    ]
  },
  "cm-shipzzer-row": {
    "width": 1920,
    "height": 410,
    "originalBytes": 220157,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-row-320.webp",
        "bytes": 4452
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-row-640.webp",
        "bytes": 12718
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-row-1024.webp",
        "bytes": 25512
      }
    ]
  },
  "cm-shipzzer-tracking": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 621354,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-tracking-320.webp",
        "bytes": 9882
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-tracking-640.webp",
        "bytes": 25994
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-tracking-1024.webp",
        "bytes": 46434
      }
    ]
  },
  "founder": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1290822,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/founder-320.webp",
        "bytes": 4982
      },
      {
        "width": 640,
        "src": "/responsive/founder-640.webp",
        "bytes": 11656
      },
      {
        "width": 1024,
        "src": "/responsive/founder-1024.webp",
        "bytes": 23788
      }
    ]
  },
  "growapp-logo": {
    "width": 200,
    "height": 200,
    "originalBytes": 3966,
    "variants": [
      {
        "width": 200,
        "src": "/responsive/growapp-logo-200.webp",
        "bytes": 854
      }
    ]
  },
  "growapp-meta-dashboard": {
    "width": 1920,
    "height": 1259,
    "originalBytes": 317083,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/growapp-meta-dashboard-320.webp",
        "bytes": 5654
      },
      {
        "width": 640,
        "src": "/responsive/growapp-meta-dashboard-640.webp",
        "bytes": 17814
      },
      {
        "width": 1024,
        "src": "/responsive/growapp-meta-dashboard-1024.webp",
        "bytes": 35928
      }
    ]
  },
  "ic-center-full-landing": {
    "width": 597,
    "height": 1920,
    "originalBytes": 208814,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ic-center-full-landing-320.webp",
        "bytes": 21336
      }
    ]
  },
  "ic-center-hero": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 461006,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ic-center-hero-320.webp",
        "bytes": 4464
      },
      {
        "width": 640,
        "src": "/responsive/ic-center-hero-640.webp",
        "bytes": 12432
      },
      {
        "width": 1024,
        "src": "/responsive/ic-center-hero-1024.webp",
        "bytes": 23728
      }
    ]
  },
  "khoubeib": {
    "width": 300,
    "height": 298,
    "originalBytes": 139829,
    "variants": [
      {
        "width": 300,
        "src": "/responsive/khoubeib-300.webp",
        "bytes": 3328
      }
    ]
  },
  "landing-bottlenexus": {
    "width": 1920,
    "height": 994,
    "originalBytes": 731822,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-bottlenexus-320.webp",
        "bytes": 5840
      },
      {
        "width": 640,
        "src": "/responsive/landing-bottlenexus-640.webp",
        "bytes": 14490
      },
      {
        "width": 1024,
        "src": "/responsive/landing-bottlenexus-1024.webp",
        "bytes": 25616
      }
    ]
  },
  "landing-clarrio": {
    "width": 1920,
    "height": 992,
    "originalBytes": 960850,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-clarrio-320.webp",
        "bytes": 3686
      },
      {
        "width": 640,
        "src": "/responsive/landing-clarrio-640.webp",
        "bytes": 10792
      },
      {
        "width": 1024,
        "src": "/responsive/landing-clarrio-1024.webp",
        "bytes": 20688
      }
    ]
  },
  "landing-page-playbook-3d": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 295726,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-page-playbook-3d-320.webp",
        "bytes": 7568
      },
      {
        "width": 640,
        "src": "/responsive/landing-page-playbook-3d-640.webp",
        "bytes": 17440
      },
      {
        "width": 1024,
        "src": "/responsive/landing-page-playbook-3d-1024.webp",
        "bytes": 26584
      }
    ]
  },
  "landing-pubwrite": {
    "width": 1920,
    "height": 1034,
    "originalBytes": 687177,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-pubwrite-320.webp",
        "bytes": 3612
      },
      {
        "width": 640,
        "src": "/responsive/landing-pubwrite-640.webp",
        "bytes": 10516
      },
      {
        "width": 1024,
        "src": "/responsive/landing-pubwrite-1024.webp",
        "bytes": 21128
      }
    ]
  },
  "landing-screenplay": {
    "width": 1920,
    "height": 1038,
    "originalBytes": 76194,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-screenplay-320.webp",
        "bytes": 3400
      },
      {
        "width": 640,
        "src": "/responsive/landing-screenplay-640.webp",
        "bytes": 10026
      },
      {
        "width": 1024,
        "src": "/responsive/landing-screenplay-1024.webp",
        "bytes": 19070
      }
    ]
  },
  "landing-shipzzer": {
    "width": 1920,
    "height": 996,
    "originalBytes": 607266,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-shipzzer-320.webp",
        "bytes": 5994
      },
      {
        "width": 640,
        "src": "/responsive/landing-shipzzer-640.webp",
        "bytes": 14836
      },
      {
        "width": 1024,
        "src": "/responsive/landing-shipzzer-1024.webp",
        "bytes": 26502
      }
    ]
  },
  "landing-zembra": {
    "width": 1920,
    "height": 993,
    "originalBytes": 366273,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-zembra-320.webp",
        "bytes": 3870
      },
      {
        "width": 640,
        "src": "/responsive/landing-zembra-640.webp",
        "bytes": 11020
      },
      {
        "width": 1024,
        "src": "/responsive/landing-zembra-1024.webp",
        "bytes": 24004
      }
    ]
  },
  "meta-ads-dashboard": {
    "width": 1920,
    "height": 1019,
    "originalBytes": 277023,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/meta-ads-dashboard-320.webp",
        "bytes": 4140
      },
      {
        "width": 640,
        "src": "/responsive/meta-ads-dashboard-640.webp",
        "bytes": 12138
      },
      {
        "width": 1024,
        "src": "/responsive/meta-ads-dashboard-1024.webp",
        "bytes": 26440
      }
    ]
  },
  "playbook-preview-1": {
    "width": 800,
    "height": 600,
    "originalBytes": 246323,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-1-320.webp",
        "bytes": 6250
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-1-640.webp",
        "bytes": 16648
      }
    ]
  },
  "playbook-preview-2": {
    "width": 800,
    "height": 600,
    "originalBytes": 244550,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-2-320.webp",
        "bytes": 6512
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-2-640.webp",
        "bytes": 16860
      }
    ]
  },
  "playbook-preview-3": {
    "width": 800,
    "height": 600,
    "originalBytes": 463255,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-3-320.webp",
        "bytes": 11296
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-3-640.webp",
        "bytes": 30660
      }
    ]
  },
  "pubrella-after": {
    "width": 1000,
    "height": 6251,
    "originalBytes": 762703,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-after-320.webp",
        "bytes": 34228
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-after-640.webp",
        "bytes": 106678
      }
    ]
  },
  "pubrella-before": {
    "width": 1000,
    "height": 6625,
    "originalBytes": 865369,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-before-320.webp",
        "bytes": 36434
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-before-640.webp",
        "bytes": 120958
      }
    ]
  },
  "pubrella-screenshot": {
    "width": 1920,
    "height": 1080,
    "originalBytes": 726804,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-screenshot-320.webp",
        "bytes": 3790
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-screenshot-640.webp",
        "bytes": 10572
      },
      {
        "width": 1024,
        "src": "/responsive/pubrella-screenshot-1024.webp",
        "bytes": 22030
      }
    ]
  },
  "saas-video-cover": {
    "width": 900,
    "height": 475,
    "originalBytes": 66499,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-video-cover-320.webp",
        "bytes": 5066
      },
      {
        "width": 640,
        "src": "/responsive/saas-video-cover-640.webp",
        "bytes": 10602
      }
    ]
  },
  "screenplay-dashboard": {
    "width": 1920,
    "height": 1080,
    "originalBytes": 113969,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-dashboard-320.webp",
        "bytes": 3424
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-dashboard-640.webp",
        "bytes": 10752
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-dashboard-1024.webp",
        "bytes": 21674
      }
    ]
  },
  "screenplay-hero-screenshot": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 220169,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-hero-screenshot-320.webp",
        "bytes": 4128
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-hero-screenshot-640.webp",
        "bytes": 12642
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-hero-screenshot-1024.webp",
        "bytes": 23844
      }
    ]
  },
  "screenplay-new-casting": {
    "width": 1920,
    "height": 1041,
    "originalBytes": 36588,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-casting-320.webp",
        "bytes": 1436
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-casting-640.webp",
        "bytes": 4292
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-casting-1024.webp",
        "bytes": 9248
      }
    ]
  },
  "screenplay-new-studio": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 63514,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-studio-320.webp",
        "bytes": 2246
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-studio-640.webp",
        "bytes": 7366
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-studio-1024.webp",
        "bytes": 14066
      }
    ]
  },
  "screenplay-new-upload": {
    "width": 1920,
    "height": 1032,
    "originalBytes": 39746,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-upload-320.webp",
        "bytes": 2078
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-upload-640.webp",
        "bytes": 5956
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-upload-1024.webp",
        "bytes": 10780
      }
    ]
  },
  "screenplay-old-casting": {
    "width": 1920,
    "height": 1030,
    "originalBytes": 82110,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-casting-320.webp",
        "bytes": 3228
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-casting-640.webp",
        "bytes": 9666
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-casting-1024.webp",
        "bytes": 20044
      }
    ]
  },
  "screenplay-old-landing": {
    "width": 1634,
    "height": 1920,
    "originalBytes": 1116529,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-landing-320.webp",
        "bytes": 7092
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-landing-640.webp",
        "bytes": 23506
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-landing-1024.webp",
        "bytes": 46010
      }
    ]
  },
  "screenplay-old-perform": {
    "width": 1920,
    "height": 1033,
    "originalBytes": 117558,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-perform-320.webp",
        "bytes": 4728
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-perform-640.webp",
        "bytes": 14520
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-perform-1024.webp",
        "bytes": 27026
      }
    ]
  },
  "screenplay-old-pricing": {
    "width": 1920,
    "height": 1029,
    "originalBytes": 127676,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-pricing-320.webp",
        "bytes": 5050
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-pricing-640.webp",
        "bytes": 15876
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-pricing-1024.webp",
        "bytes": 29752
      }
    ]
  },
  "shipzzer-logo-white": {
    "width": 256,
    "height": 27,
    "originalBytes": 2520,
    "variants": [
      {
        "width": 256,
        "src": "/responsive/shipzzer-logo-white-256.webp",
        "bytes": 1480
      }
    ]
  },
  "shipzzer-logo": {
    "width": 256,
    "height": 27,
    "originalBytes": 2520,
    "variants": [
      {
        "width": 256,
        "src": "/responsive/shipzzer-logo-256.webp",
        "bytes": 1480
      }
    ]
  },
  "shipzzer-new-landing": {
    "width": 337,
    "height": 1920,
    "originalBytes": 424350,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/shipzzer-new-landing-320.webp",
        "bytes": 45860
      }
    ]
  },
  "shipzzer-old-landing": {
    "width": 399,
    "height": 1920,
    "originalBytes": 388658,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/shipzzer-old-landing-320.webp",
        "bytes": 36656
      }
    ]
  },
  "tiktok-cover": {
    "width": 624,
    "height": 900,
    "originalBytes": 100265,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/tiktok-cover-320.webp",
        "bytes": 10088
      }
    ]
  },
  "youtube-cover": {
    "width": 900,
    "height": 534,
    "originalBytes": 163757,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/youtube-cover-320.webp",
        "bytes": 11558
      },
      {
        "width": 640,
        "src": "/responsive/youtube-cover-640.webp",
        "bytes": 32720
      }
    ]
  },
  "zembra-old-website": {
    "width": 1920,
    "height": 909,
    "originalBytes": 68808,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/zembra-old-website-320.webp",
        "bytes": 3626
      },
      {
        "width": 640,
        "src": "/responsive/zembra-old-website-640.webp",
        "bytes": 10904
      },
      {
        "width": 1024,
        "src": "/responsive/zembra-old-website-1024.webp",
        "bytes": 19028
      }
    ]
  },
  "hero-portrait": {
    "width": 595,
    "height": 734,
    "originalBytes": 34864,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/hero-portrait-320.webp",
        "bytes": 12286
      }
    ]
  },
  "khoubeib-96": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 902556,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/khoubeib-96-320.webp",
        "bytes": 3154
      },
      {
        "width": 640,
        "src": "/responsive/khoubeib-96-640.webp",
        "bytes": 7350
      },
      {
        "width": 1024,
        "src": "/responsive/khoubeib-96-1024.webp",
        "bytes": 13508
      }
    ]
  }
} as const satisfies Record<string, ResponsiveImageEntry>;
