// Generated by scripts/generate-responsive-images.mjs. Do not edit by hand.
export type ResponsiveImageVariant = {
  width: number;
  src: string;
  bytes: number;
};

export type ResponsiveImageEntry = {
  width: number;
  height: number;
  originalBytes: number;
  variants: ResponsiveImageVariant[];
};

export const responsiveImageManifest = {
  "ad-creative-1": {
    "width": 900,
    "height": 900,
    "originalBytes": 140857,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-1-320.webp",
        "bytes": 9884
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-1-640.webp",
        "bytes": 21150
      }
    ]
  },
  "ad-creative-2": {
    "width": 900,
    "height": 900,
    "originalBytes": 156943,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-2-320.webp",
        "bytes": 9350
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-2-640.webp",
        "bytes": 22694
      }
    ]
  },
  "ad-creative-3": {
    "width": 900,
    "height": 900,
    "originalBytes": 197647,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-3-320.webp",
        "bytes": 11280
      },
      {
        "width": 640,
        "src": "/responsive/ad-creative-3-640.webp",
        "bytes": 28520
      }
    ]
  },
  "ad-creative-4": {
    "width": 506,
    "height": 900,
    "originalBytes": 108665,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ad-creative-4-320.webp",
        "bytes": 16140
      }
    ]
  },
  "cm-clarrio-1": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 406369,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-clarrio-1-320.webp",
        "bytes": 10252
      },
      {
        "width": 640,
        "src": "/responsive/cm-clarrio-1-640.webp",
        "bytes": 24820
      },
      {
        "width": 1024,
        "src": "/responsive/cm-clarrio-1-1024.webp",
        "bytes": 60730
      }
    ]
  },
  "cm-clarrio-2": {
    "width": 1400,
    "height": 933,
    "originalBytes": 482393,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-clarrio-2-320.webp",
        "bytes": 6256
      },
      {
        "width": 640,
        "src": "/responsive/cm-clarrio-2-640.webp",
        "bytes": 14954
      },
      {
        "width": 1024,
        "src": "/responsive/cm-clarrio-2-1024.webp",
        "bytes": 29838
      }
    ]
  },
  "cm-foodcost": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1038505,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-foodcost-320.webp",
        "bytes": 7030
      },
      {
        "width": 640,
        "src": "/responsive/cm-foodcost-640.webp",
        "bytes": 17540
      },
      {
        "width": 1024,
        "src": "/responsive/cm-foodcost-1024.webp",
        "bytes": 30534
      }
    ]
  },
  "cm-pubrella-1": {
    "width": 1024,
    "height": 1536,
    "originalBytes": 770884,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-pubrella-1-320.webp",
        "bytes": 15640
      },
      {
        "width": 640,
        "src": "/responsive/cm-pubrella-1-640.webp",
        "bytes": 46918
      },
      {
        "width": 1024,
        "src": "/responsive/cm-pubrella-1-1024.webp",
        "bytes": 118390
      }
    ]
  },
  "cm-pubrella-2": {
    "width": 1024,
    "height": 1536,
    "originalBytes": 819839,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-pubrella-2-320.webp",
        "bytes": 14666
      },
      {
        "width": 640,
        "src": "/responsive/cm-pubrella-2-640.webp",
        "bytes": 34454
      },
      {
        "width": 1024,
        "src": "/responsive/cm-pubrella-2-1024.webp",
        "bytes": 64720
      }
    ]
  },
  "cm-shipzzer-collage": {
    "width": 1920,
    "height": 886,
    "originalBytes": 616747,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-collage-320.webp",
        "bytes": 9408
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-collage-640.webp",
        "bytes": 26880
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-collage-1024.webp",
        "bytes": 53374
      }
    ]
  },
  "cm-shipzzer-invoices": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1128632,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-invoices-320.webp",
        "bytes": 9666
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-invoices-640.webp",
        "bytes": 21322
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-invoices-1024.webp",
        "bytes": 39112
      }
    ]
  },
  "cm-shipzzer-repair": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1242929,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-repair-320.webp",
        "bytes": 10308
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-repair-640.webp",
        "bytes": 24680
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-repair-1024.webp",
        "bytes": 44160
      }
    ]
  },
  "cm-shipzzer-row": {
    "width": 1920,
    "height": 410,
    "originalBytes": 220157,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-row-320.webp",
        "bytes": 4452
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-row-640.webp",
        "bytes": 12718
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-row-1024.webp",
        "bytes": 25512
      }
    ]
  },
  "cm-shipzzer-tracking": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 621354,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cm-shipzzer-tracking-320.webp",
        "bytes": 9882
      },
      {
        "width": 640,
        "src": "/responsive/cm-shipzzer-tracking-640.webp",
        "bytes": 25994
      },
      {
        "width": 1024,
        "src": "/responsive/cm-shipzzer-tracking-1024.webp",
        "bytes": 46434
      }
    ]
  },
  "founder": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 1290822,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/founder-320.webp",
        "bytes": 4982
      },
      {
        "width": 640,
        "src": "/responsive/founder-640.webp",
        "bytes": 11656
      },
      {
        "width": 1024,
        "src": "/responsive/founder-1024.webp",
        "bytes": 23788
      }
    ]
  },
  "growapp-logo": {
    "width": 200,
    "height": 200,
    "originalBytes": 3966,
    "variants": [
      {
        "width": 200,
        "src": "/responsive/growapp-logo-200.webp",
        "bytes": 854
      }
    ]
  },
  "growapp-meta-dashboard": {
    "width": 1920,
    "height": 1259,
    "originalBytes": 317083,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/growapp-meta-dashboard-320.webp",
        "bytes": 5654
      },
      {
        "width": 640,
        "src": "/responsive/growapp-meta-dashboard-640.webp",
        "bytes": 17814
      },
      {
        "width": 1024,
        "src": "/responsive/growapp-meta-dashboard-1024.webp",
        "bytes": 35928
      }
    ]
  },
  "ic-center-full-landing": {
    "width": 597,
    "height": 1920,
    "originalBytes": 208814,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ic-center-full-landing-320.webp",
        "bytes": 21336
      }
    ]
  },
  "ic-center-hero": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 461006,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/ic-center-hero-320.webp",
        "bytes": 4464
      },
      {
        "width": 640,
        "src": "/responsive/ic-center-hero-640.webp",
        "bytes": 12432
      },
      {
        "width": 1024,
        "src": "/responsive/ic-center-hero-1024.webp",
        "bytes": 23728
      }
    ]
  },
  "khoubeib": {
    "width": 300,
    "height": 298,
    "originalBytes": 139829,
    "variants": [
      {
        "width": 300,
        "src": "/responsive/khoubeib-300.webp",
        "bytes": 3328
      }
    ]
  },
  "landing-bottlenexus": {
    "width": 1920,
    "height": 994,
    "originalBytes": 731822,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-bottlenexus-320.webp",
        "bytes": 5840
      },
      {
        "width": 640,
        "src": "/responsive/landing-bottlenexus-640.webp",
        "bytes": 14490
      },
      {
        "width": 1024,
        "src": "/responsive/landing-bottlenexus-1024.webp",
        "bytes": 25616
      }
    ]
  },
  "landing-clarrio": {
    "width": 1920,
    "height": 992,
    "originalBytes": 960850,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-clarrio-320.webp",
        "bytes": 3686
      },
      {
        "width": 640,
        "src": "/responsive/landing-clarrio-640.webp",
        "bytes": 10792
      },
      {
        "width": 1024,
        "src": "/responsive/landing-clarrio-1024.webp",
        "bytes": 20688
      }
    ]
  },
  "landing-page-playbook-3d": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 295726,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-page-playbook-3d-320.webp",
        "bytes": 7568
      },
      {
        "width": 640,
        "src": "/responsive/landing-page-playbook-3d-640.webp",
        "bytes": 17440
      },
      {
        "width": 1024,
        "src": "/responsive/landing-page-playbook-3d-1024.webp",
        "bytes": 26584
      }
    ]
  },
  "landing-pubwrite": {
    "width": 1920,
    "height": 1034,
    "originalBytes": 687177,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-pubwrite-320.webp",
        "bytes": 3612
      },
      {
        "width": 640,
        "src": "/responsive/landing-pubwrite-640.webp",
        "bytes": 10516
      },
      {
        "width": 1024,
        "src": "/responsive/landing-pubwrite-1024.webp",
        "bytes": 21128
      }
    ]
  },
  "landing-screenplay": {
    "width": 1920,
    "height": 1038,
    "originalBytes": 76194,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-screenplay-320.webp",
        "bytes": 3400
      },
      {
        "width": 640,
        "src": "/responsive/landing-screenplay-640.webp",
        "bytes": 10026
      },
      {
        "width": 1024,
        "src": "/responsive/landing-screenplay-1024.webp",
        "bytes": 19070
      }
    ]
  },
  "landing-shipzzer": {
    "width": 1920,
    "height": 996,
    "originalBytes": 607266,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-shipzzer-320.webp",
        "bytes": 5994
      },
      {
        "width": 640,
        "src": "/responsive/landing-shipzzer-640.webp",
        "bytes": 14836
      },
      {
        "width": 1024,
        "src": "/responsive/landing-shipzzer-1024.webp",
        "bytes": 26502
      }
    ]
  },
  "landing-zembra": {
    "width": 1920,
    "height": 993,
    "originalBytes": 366273,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-zembra-320.webp",
        "bytes": 3870
      },
      {
        "width": 640,
        "src": "/responsive/landing-zembra-640.webp",
        "bytes": 11020
      },
      {
        "width": 1024,
        "src": "/responsive/landing-zembra-1024.webp",
        "bytes": 24004
      }
    ]
  },
  "meta-ads-dashboard": {
    "width": 1920,
    "height": 1019,
    "originalBytes": 277023,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/meta-ads-dashboard-320.webp",
        "bytes": 4140
      },
      {
        "width": 640,
        "src": "/responsive/meta-ads-dashboard-640.webp",
        "bytes": 12138
      },
      {
        "width": 1024,
        "src": "/responsive/meta-ads-dashboard-1024.webp",
        "bytes": 26440
      }
    ]
  },
  "playbook-preview-1": {
    "width": 800,
    "height": 600,
    "originalBytes": 246323,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-1-320.webp",
        "bytes": 6250
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-1-640.webp",
        "bytes": 16648
      }
    ]
  },
  "playbook-preview-2": {
    "width": 800,
    "height": 600,
    "originalBytes": 244550,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-2-320.webp",
        "bytes": 6512
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-2-640.webp",
        "bytes": 16860
      }
    ]
  },
  "playbook-preview-3": {
    "width": 800,
    "height": 600,
    "originalBytes": 463255,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/playbook-preview-3-320.webp",
        "bytes": 11296
      },
      {
        "width": 640,
        "src": "/responsive/playbook-preview-3-640.webp",
        "bytes": 30660
      }
    ]
  },
  "pubrella-after": {
    "width": 1000,
    "height": 6251,
    "originalBytes": 762703,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-after-320.webp",
        "bytes": 34228
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-after-640.webp",
        "bytes": 106678
      }
    ]
  },
  "pubrella-before": {
    "width": 1000,
    "height": 6625,
    "originalBytes": 865369,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-before-320.webp",
        "bytes": 36434
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-before-640.webp",
        "bytes": 120958
      }
    ]
  },
  "pubrella-screenshot": {
    "width": 1920,
    "height": 1080,
    "originalBytes": 726804,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/pubrella-screenshot-320.webp",
        "bytes": 3790
      },
      {
        "width": 640,
        "src": "/responsive/pubrella-screenshot-640.webp",
        "bytes": 10572
      },
      {
        "width": 1024,
        "src": "/responsive/pubrella-screenshot-1024.webp",
        "bytes": 22030
      }
    ]
  },
  "saas-video-cover": {
    "width": 900,
    "height": 475,
    "originalBytes": 66499,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-video-cover-320.webp",
        "bytes": 5066
      },
      {
        "width": 640,
        "src": "/responsive/saas-video-cover-640.webp",
        "bytes": 10602
      }
    ]
  },
  "screenplay-dashboard": {
    "width": 1920,
    "height": 1080,
    "originalBytes": 113969,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-dashboard-320.webp",
        "bytes": 3424
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-dashboard-640.webp",
        "bytes": 10752
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-dashboard-1024.webp",
        "bytes": 21674
      }
    ]
  },
  "screenplay-hero-screenshot": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 220169,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-hero-screenshot-320.webp",
        "bytes": 4128
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-hero-screenshot-640.webp",
        "bytes": 12642
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-hero-screenshot-1024.webp",
        "bytes": 23844
      }
    ]
  },
  "screenplay-new-casting": {
    "width": 1920,
    "height": 1041,
    "originalBytes": 36588,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-casting-320.webp",
        "bytes": 1436
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-casting-640.webp",
        "bytes": 4292
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-casting-1024.webp",
        "bytes": 9248
      }
    ]
  },
  "screenplay-new-studio": {
    "width": 1920,
    "height": 1035,
    "originalBytes": 63514,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-studio-320.webp",
        "bytes": 2246
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-studio-640.webp",
        "bytes": 7366
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-studio-1024.webp",
        "bytes": 14066
      }
    ]
  },
  "screenplay-new-upload": {
    "width": 1920,
    "height": 1032,
    "originalBytes": 39746,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-new-upload-320.webp",
        "bytes": 2078
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-new-upload-640.webp",
        "bytes": 5956
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-new-upload-1024.webp",
        "bytes": 10780
      }
    ]
  },
  "screenplay-old-casting": {
    "width": 1920,
    "height": 1030,
    "originalBytes": 82110,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-casting-320.webp",
        "bytes": 3228
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-casting-640.webp",
        "bytes": 9666
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-casting-1024.webp",
        "bytes": 20044
      }
    ]
  },
  "screenplay-old-landing": {
    "width": 1634,
    "height": 1920,
    "originalBytes": 1116529,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-landing-320.webp",
        "bytes": 7092
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-landing-640.webp",
        "bytes": 23506
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-landing-1024.webp",
        "bytes": 46010
      }
    ]
  },
  "screenplay-old-perform": {
    "width": 1920,
    "height": 1033,
    "originalBytes": 117558,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-perform-320.webp",
        "bytes": 4728
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-perform-640.webp",
        "bytes": 14520
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-perform-1024.webp",
        "bytes": 27026
      }
    ]
  },
  "screenplay-old-pricing": {
    "width": 1920,
    "height": 1029,
    "originalBytes": 127676,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/screenplay-old-pricing-320.webp",
        "bytes": 5050
      },
      {
        "width": 640,
        "src": "/responsive/screenplay-old-pricing-640.webp",
        "bytes": 15876
      },
      {
        "width": 1024,
        "src": "/responsive/screenplay-old-pricing-1024.webp",
        "bytes": 29752
      }
    ]
  },
  "shipzzer-logo-white": {
    "width": 256,
    "height": 27,
    "originalBytes": 2520,
    "variants": [
      {
        "width": 256,
        "src": "/responsive/shipzzer-logo-white-256.webp",
        "bytes": 1480
      }
    ]
  },
  "shipzzer-logo": {
    "width": 256,
    "height": 27,
    "originalBytes": 2520,
    "variants": [
      {
        "width": 256,
        "src": "/responsive/shipzzer-logo-256.webp",
        "bytes": 1480
      }
    ]
  },
  "shipzzer-new-landing": {
    "width": 337,
    "height": 1920,
    "originalBytes": 424350,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/shipzzer-new-landing-320.webp",
        "bytes": 45860
      }
    ]
  },
  "shipzzer-old-landing": {
    "width": 399,
    "height": 1920,
    "originalBytes": 388658,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/shipzzer-old-landing-320.webp",
        "bytes": 36656
      }
    ]
  },
  "tiktok-cover": {
    "width": 624,
    "height": 900,
    "originalBytes": 100265,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/tiktok-cover-320.webp",
        "bytes": 10088
      }
    ]
  },
  "youtube-cover": {
    "width": 900,
    "height": 534,
    "originalBytes": 163757,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/youtube-cover-320.webp",
        "bytes": 11558
      },
      {
        "width": 640,
        "src": "/responsive/youtube-cover-640.webp",
        "bytes": 32720
      }
    ]
  },
  "zembra-old-website": {
    "width": 1920,
    "height": 909,
    "originalBytes": 68808,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/zembra-old-website-320.webp",
        "bytes": 3626
      },
      {
        "width": 640,
        "src": "/responsive/zembra-old-website-640.webp",
        "bytes": 10904
      },
      {
        "width": 1024,
        "src": "/responsive/zembra-old-website-1024.webp",
        "bytes": 19028
      }
    ]
  },
  "landing-page-for-saas": {
    "width": 1854,
    "height": 848,
    "originalBytes": 62692,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-page-for-saas-320.webp",
        "bytes": 3032
      },
      {
        "width": 640,
        "src": "/responsive/landing-page-for-saas-640.webp",
        "bytes": 9122
      },
      {
        "width": 1024,
        "src": "/responsive/landing-page-for-saas-1024.webp",
        "bytes": 18536
      }
    ]
  },
  "b2b-saas-marketing-strategy-framework-wael-aouididi": {
    "width": 1376,
    "height": 768,
    "originalBytes": 638458,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/b2b-saas-marketing-strategy-framework-wael-aouididi-320.webp",
        "bytes": 3640
      },
      {
        "width": 640,
        "src": "/responsive/b2b-saas-marketing-strategy-framework-wael-aouididi-640.webp",
        "bytes": 8586
      },
      {
        "width": 1024,
        "src": "/responsive/b2b-saas-marketing-strategy-framework-wael-aouididi-1024.webp",
        "bytes": 14648
      }
    ]
  },
  "cold-email-for-saas-outreach-strategy-wael-aouididi": {
    "width": 1672,
    "height": 941,
    "originalBytes": 54416,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cold-email-for-saas-outreach-strategy-wael-aouididi-320.webp",
        "bytes": 3494
      },
      {
        "width": 640,
        "src": "/responsive/cold-email-for-saas-outreach-strategy-wael-aouididi-640.webp",
        "bytes": 9712
      },
      {
        "width": 1024,
        "src": "/responsive/cold-email-for-saas-outreach-strategy-wael-aouididi-1024.webp",
        "bytes": 19750
      }
    ]
  },
  "cold-email-for-saas": {
    "width": 1672,
    "height": 941,
    "originalBytes": 54416,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/cold-email-for-saas-320.webp",
        "bytes": 3494
      },
      {
        "width": 640,
        "src": "/responsive/cold-email-for-saas-640.webp",
        "bytes": 9712
      },
      {
        "width": 1024,
        "src": "/responsive/cold-email-for-saas-1024.webp",
        "bytes": 19750
      }
    ]
  },
  "2019-01": {
    "width": 1455,
    "height": 8015,
    "originalBytes": 372274,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2019-01-320.webp",
        "bytes": 24736
      },
      {
        "width": 640,
        "src": "/responsive/2019-01-640.webp",
        "bytes": 70810
      },
      {
        "width": 1024,
        "src": "/responsive/2019-01-1024.webp",
        "bytes": 121564
      }
    ]
  },
  "2019-04": {
    "width": 1455,
    "height": 8015,
    "originalBytes": 370270,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2019-04-320.webp",
        "bytes": 24600
      },
      {
        "width": 640,
        "src": "/responsive/2019-04-640.webp",
        "bytes": 70194
      },
      {
        "width": 1024,
        "src": "/responsive/2019-04-1024.webp",
        "bytes": 121480
      }
    ]
  },
  "2019-07": {
    "width": 1440,
    "height": 7267,
    "originalBytes": 357766,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2019-07-320.webp",
        "bytes": 29324
      },
      {
        "width": 640,
        "src": "/responsive/2019-07-640.webp",
        "bytes": 81534
      },
      {
        "width": 1024,
        "src": "/responsive/2019-07-1024.webp",
        "bytes": 131766
      }
    ]
  },
  "2019-10": {
    "width": 1440,
    "height": 7135,
    "originalBytes": 352092,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2019-10-320.webp",
        "bytes": 28776
      },
      {
        "width": 640,
        "src": "/responsive/2019-10-640.webp",
        "bytes": 80124
      },
      {
        "width": 1024,
        "src": "/responsive/2019-10-1024.webp",
        "bytes": 129876
      }
    ]
  },
  "2020-01": {
    "width": 1440,
    "height": 7211,
    "originalBytes": 356676,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2020-01-320.webp",
        "bytes": 29054
      },
      {
        "width": 640,
        "src": "/responsive/2020-01-640.webp",
        "bytes": 80334
      },
      {
        "width": 1024,
        "src": "/responsive/2020-01-1024.webp",
        "bytes": 131488
      }
    ]
  },
  "2020-04": {
    "width": 1440,
    "height": 8920,
    "originalBytes": 506650,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2020-04-320.webp",
        "bytes": 38294
      },
      {
        "width": 640,
        "src": "/responsive/2020-04-640.webp",
        "bytes": 107418
      },
      {
        "width": 1024,
        "src": "/responsive/2020-04-1024.webp",
        "bytes": 175408
      }
    ]
  },
  "2020-07": {
    "width": 1440,
    "height": 8927,
    "originalBytes": 514258,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2020-07-320.webp",
        "bytes": 38510
      },
      {
        "width": 640,
        "src": "/responsive/2020-07-640.webp",
        "bytes": 108440
      },
      {
        "width": 1024,
        "src": "/responsive/2020-07-1024.webp",
        "bytes": 176594
      }
    ]
  },
  "2020-10": {
    "width": 1440,
    "height": 8898,
    "originalBytes": 509016,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2020-10-320.webp",
        "bytes": 38682
      },
      {
        "width": 640,
        "src": "/responsive/2020-10-640.webp",
        "bytes": 110108
      },
      {
        "width": 1024,
        "src": "/responsive/2020-10-1024.webp",
        "bytes": 174368
      }
    ]
  },
  "2021-01": {
    "width": 1440,
    "height": 9022,
    "originalBytes": 512852,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2021-01-320.webp",
        "bytes": 39168
      },
      {
        "width": 640,
        "src": "/responsive/2021-01-640.webp",
        "bytes": 111026
      },
      {
        "width": 1024,
        "src": "/responsive/2021-01-1024.webp",
        "bytes": 177132
      }
    ]
  },
  "2021-04": {
    "width": 1440,
    "height": 9023,
    "originalBytes": 405316,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2021-04-320.webp",
        "bytes": 31022
      },
      {
        "width": 640,
        "src": "/responsive/2021-04-640.webp",
        "bytes": 90168
      },
      {
        "width": 1024,
        "src": "/responsive/2021-04-1024.webp",
        "bytes": 146330
      }
    ]
  },
  "2022-04": {
    "width": 1440,
    "height": 7593,
    "originalBytes": 376214,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2022-04-320.webp",
        "bytes": 24154
      },
      {
        "width": 640,
        "src": "/responsive/2022-04-640.webp",
        "bytes": 74790
      },
      {
        "width": 1024,
        "src": "/responsive/2022-04-1024.webp",
        "bytes": 125674
      }
    ]
  },
  "2022-10": {
    "width": 1440,
    "height": 8063,
    "originalBytes": 398458,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2022-10-320.webp",
        "bytes": 25232
      },
      {
        "width": 640,
        "src": "/responsive/2022-10-640.webp",
        "bytes": 80652
      },
      {
        "width": 1024,
        "src": "/responsive/2022-10-1024.webp",
        "bytes": 135830
      }
    ]
  },
  "2023-07": {
    "width": 1452,
    "height": 16000,
    "originalBytes": 726528,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2023-07-320.webp",
        "bytes": 39726
      },
      {
        "width": 640,
        "src": "/responsive/2023-07-640.webp",
        "bytes": 117068
      },
      {
        "width": 1024,
        "src": "/responsive/2023-07-1024.webp",
        "bytes": 222918
      }
    ]
  },
  "2023-10": {
    "width": 1440,
    "height": 5556,
    "originalBytes": 443718,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2023-10-320.webp",
        "bytes": 32896
      },
      {
        "width": 640,
        "src": "/responsive/2023-10-640.webp",
        "bytes": 93968
      },
      {
        "width": 1024,
        "src": "/responsive/2023-10-1024.webp",
        "bytes": 149226
      }
    ]
  },
  "2024-01": {
    "width": 1440,
    "height": 13157,
    "originalBytes": 561106,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2024-01-320.webp",
        "bytes": 35722
      },
      {
        "width": 640,
        "src": "/responsive/2024-01-640.webp",
        "bytes": 111798
      },
      {
        "width": 1024,
        "src": "/responsive/2024-01-1024.webp",
        "bytes": 188260
      }
    ]
  },
  "2024-04": {
    "width": 1440,
    "height": 9446,
    "originalBytes": 450938,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2024-04-320.webp",
        "bytes": 30652
      },
      {
        "width": 640,
        "src": "/responsive/2024-04-640.webp",
        "bytes": 95236
      },
      {
        "width": 1024,
        "src": "/responsive/2024-04-1024.webp",
        "bytes": 162964
      }
    ]
  },
  "2024-07": {
    "width": 1440,
    "height": 13174,
    "originalBytes": 557798,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2024-07-320.webp",
        "bytes": 35764
      },
      {
        "width": 640,
        "src": "/responsive/2024-07-640.webp",
        "bytes": 111836
      },
      {
        "width": 1024,
        "src": "/responsive/2024-07-1024.webp",
        "bytes": 190454
      }
    ]
  },
  "2025-04": {
    "width": 1440,
    "height": 9625,
    "originalBytes": 743098,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2025-04-320.webp",
        "bytes": 51884
      },
      {
        "width": 640,
        "src": "/responsive/2025-04-640.webp",
        "bytes": 131902
      },
      {
        "width": 1024,
        "src": "/responsive/2025-04-1024.webp",
        "bytes": 255728
      }
    ]
  },
  "2025-07": {
    "width": 1440,
    "height": 14364,
    "originalBytes": 485506,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2025-07-320.webp",
        "bytes": 35282
      },
      {
        "width": 640,
        "src": "/responsive/2025-07-640.webp",
        "bytes": 108102
      },
      {
        "width": 1024,
        "src": "/responsive/2025-07-1024.webp",
        "bytes": 181868
      }
    ]
  },
  "2025-10": {
    "width": 1440,
    "height": 9995,
    "originalBytes": 758866,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2025-10-320.webp",
        "bytes": 51686
      },
      {
        "width": 640,
        "src": "/responsive/2025-10-640.webp",
        "bytes": 133036
      },
      {
        "width": 1024,
        "src": "/responsive/2025-10-1024.webp",
        "bytes": 254094
      }
    ]
  },
  "2026-01": {
    "width": 1440,
    "height": 9467,
    "originalBytes": 744260,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2026-01-320.webp",
        "bytes": 53016
      },
      {
        "width": 640,
        "src": "/responsive/2026-01-640.webp",
        "bytes": 132694
      },
      {
        "width": 1024,
        "src": "/responsive/2026-01-1024.webp",
        "bytes": 254874
      }
    ]
  },
  "2026-04": {
    "width": 1440,
    "height": 14601,
    "originalBytes": 778682,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2026-04-320.webp",
        "bytes": 42754
      },
      {
        "width": 640,
        "src": "/responsive/2026-04-640.webp",
        "bytes": 118224
      },
      {
        "width": 1024,
        "src": "/responsive/2026-04-1024.webp",
        "bytes": 233488
      }
    ]
  },
  "current-live": {
    "width": 1440,
    "height": 9326,
    "originalBytes": 856876,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/current-live-320.webp",
        "bytes": 57384
      },
      {
        "width": 640,
        "src": "/responsive/current-live-640.webp",
        "bytes": 143742
      },
      {
        "width": 1024,
        "src": "/responsive/current-live-1024.webp",
        "bytes": 271980
      }
    ]
  },
  "2021-10": {
    "width": 1440,
    "height": 6356,
    "originalBytes": 484590,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2021-10-320.webp",
        "bytes": 31614
      },
      {
        "width": 640,
        "src": "/responsive/2021-10-640.webp",
        "bytes": 97052
      },
      {
        "width": 1024,
        "src": "/responsive/2021-10-1024.webp",
        "bytes": 157786
      }
    ]
  },
  "2022-07": {
    "width": 1440,
    "height": 9572,
    "originalBytes": 484132,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2022-07-320.webp",
        "bytes": 35220
      },
      {
        "width": 640,
        "src": "/responsive/2022-07-640.webp",
        "bytes": 106776
      },
      {
        "width": 1024,
        "src": "/responsive/2022-07-1024.webp",
        "bytes": 176974
      }
    ]
  },
  "2023-04": {
    "width": 1440,
    "height": 8137,
    "originalBytes": 434166,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2023-04-320.webp",
        "bytes": 27628
      },
      {
        "width": 640,
        "src": "/responsive/2023-04-640.webp",
        "bytes": 85160
      },
      {
        "width": 1024,
        "src": "/responsive/2023-04-1024.webp",
        "bytes": 142178
      }
    ]
  },
  "2024-10": {
    "width": 1440,
    "height": 10083,
    "originalBytes": 475248,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2024-10-320.webp",
        "bytes": 33852
      },
      {
        "width": 640,
        "src": "/responsive/2024-10-640.webp",
        "bytes": 106202
      },
      {
        "width": 1024,
        "src": "/responsive/2024-10-1024.webp",
        "bytes": 176068
      }
    ]
  },
  "2022-01": {
    "width": 1440,
    "height": 11300,
    "originalBytes": 382494,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2022-01-320.webp",
        "bytes": 26482
      },
      {
        "width": 640,
        "src": "/responsive/2022-01-640.webp",
        "bytes": 79606
      },
      {
        "width": 1024,
        "src": "/responsive/2022-01-1024.webp",
        "bytes": 130680
      }
    ]
  },
  "2025-01": {
    "width": 1440,
    "height": 13246,
    "originalBytes": 557126,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2025-01-320.webp",
        "bytes": 35850
      },
      {
        "width": 640,
        "src": "/responsive/2025-01-640.webp",
        "bytes": 111884
      },
      {
        "width": 1024,
        "src": "/responsive/2025-01-1024.webp",
        "bytes": 191166
      }
    ]
  },
  "2021-07": {
    "width": 1440,
    "height": 6356,
    "originalBytes": 484590,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2021-07-320.webp",
        "bytes": 31614
      },
      {
        "width": 640,
        "src": "/responsive/2021-07-640.webp",
        "bytes": 97052
      },
      {
        "width": 1024,
        "src": "/responsive/2021-07-1024.webp",
        "bytes": 157786
      }
    ]
  },
  "2023-01": {
    "width": 1440,
    "height": 12539,
    "originalBytes": 530512,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/2023-01-320.webp",
        "bytes": 33014
      },
      {
        "width": 640,
        "src": "/responsive/2023-01-640.webp",
        "bytes": 90102
      },
      {
        "width": 1024,
        "src": "/responsive/2023-01-1024.webp",
        "bytes": 142022
      }
    ]
  },
  "hero-portrait": {
    "width": 595,
    "height": 734,
    "originalBytes": 34864,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/hero-portrait-320.webp",
        "bytes": 12286
      }
    ]
  },
  "khoubeib-96": {
    "width": 1024,
    "height": 1024,
    "originalBytes": 902556,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/khoubeib-96-320.webp",
        "bytes": 3154
      },
      {
        "width": 640,
        "src": "/responsive/khoubeib-96-640.webp",
        "bytes": 7350
      },
      {
        "width": 1024,
        "src": "/responsive/khoubeib-96-1024.webp",
        "bytes": 13508
      }
    ]
  },
  "landing-page-for-saas-freelancer": {
    "width": 1536,
    "height": 1024,
    "originalBytes": 59100,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/landing-page-for-saas-freelancer-320.webp",
        "bytes": 4498
      },
      {
        "width": 640,
        "src": "/responsive/landing-page-for-saas-freelancer-640.webp",
        "bytes": 12094
      },
      {
        "width": 1024,
        "src": "/responsive/landing-page-for-saas-freelancer-1024.webp",
        "bytes": 23770
      }
    ]
  },
  "meta-ads-for-saas-creative-funnel-conversion-wael-aouididi": {
    "width": 1935,
    "height": 813,
    "originalBytes": 63262,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/meta-ads-for-saas-creative-funnel-conversion-wael-aouididi-320.webp",
        "bytes": 3382
      },
      {
        "width": 640,
        "src": "/responsive/meta-ads-for-saas-creative-funnel-conversion-wael-aouididi-640.webp",
        "bytes": 9790
      },
      {
        "width": 1024,
        "src": "/responsive/meta-ads-for-saas-creative-funnel-conversion-wael-aouididi-1024.webp",
        "bytes": 19216
      }
    ]
  },
  "meta-ads-for-saas": {
    "width": 1935,
    "height": 813,
    "originalBytes": 63262,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/meta-ads-for-saas-320.webp",
        "bytes": 3382
      },
      {
        "width": 640,
        "src": "/responsive/meta-ads-for-saas-640.webp",
        "bytes": 9790
      },
      {
        "width": 1024,
        "src": "/responsive/meta-ads-for-saas-1024.webp",
        "bytes": 19216
      }
    ]
  },
  "one-great-book-expertise": {
    "width": 941,
    "height": 1672,
    "originalBytes": 236332,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/one-great-book-expertise-320.webp",
        "bytes": 17598
      },
      {
        "width": 640,
        "src": "/responsive/one-great-book-expertise-640.webp",
        "bytes": 47622
      }
    ]
  },
  "one-great-book-manual-vs-outline": {
    "width": 1122,
    "height": 1402,
    "originalBytes": 138954,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/one-great-book-manual-vs-outline-320.webp",
        "bytes": 11796
      },
      {
        "width": 640,
        "src": "/responsive/one-great-book-manual-vs-outline-640.webp",
        "bytes": 29024
      },
      {
        "width": 1024,
        "src": "/responsive/one-great-book-manual-vs-outline-1024.webp",
        "bytes": 48960
      }
    ]
  },
  "one-great-book-preview-toggle": {
    "width": 941,
    "height": 1672,
    "originalBytes": 113640,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/one-great-book-preview-toggle-320.webp",
        "bytes": 14446
      },
      {
        "width": 640,
        "src": "/responsive/one-great-book-preview-toggle-640.webp",
        "bytes": 31008
      }
    ]
  },
  "one-great-book-structured-authority": {
    "width": 941,
    "height": 1672,
    "originalBytes": 169996,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/one-great-book-structured-authority-320.webp",
        "bytes": 15376
      },
      {
        "width": 640,
        "src": "/responsive/one-great-book-structured-authority-640.webp",
        "bytes": 36416
      }
    ]
  },
  "saas-conversion-rate-optimisation-specialist-wael-aouididi": {
    "width": 1536,
    "height": 1024,
    "originalBytes": 59100,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-conversion-rate-optimisation-specialist-wael-aouididi-320.webp",
        "bytes": 4498
      },
      {
        "width": 640,
        "src": "/responsive/saas-conversion-rate-optimisation-specialist-wael-aouididi-640.webp",
        "bytes": 12094
      },
      {
        "width": 1024,
        "src": "/responsive/saas-conversion-rate-optimisation-specialist-wael-aouididi-1024.webp",
        "bytes": 23770
      }
    ]
  },
  "saas-landing-page-strategy-messaging-cro-wael-aouididi": {
    "width": 1854,
    "height": 848,
    "originalBytes": 62692,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-landing-page-strategy-messaging-cro-wael-aouididi-320.webp",
        "bytes": 3032
      },
      {
        "width": 640,
        "src": "/responsive/saas-landing-page-strategy-messaging-cro-wael-aouididi-640.webp",
        "bytes": 9122
      },
      {
        "width": 1024,
        "src": "/responsive/saas-landing-page-strategy-messaging-cro-wael-aouididi-1024.webp",
        "bytes": 18536
      }
    ]
  },
  "saas-marketing-agency-alternative-wael-aouididi": {
    "width": 1536,
    "height": 1024,
    "originalBytes": 52206,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-marketing-agency-alternative-wael-aouididi-320.webp",
        "bytes": 3318
      },
      {
        "width": 640,
        "src": "/responsive/saas-marketing-agency-alternative-wael-aouididi-640.webp",
        "bytes": 9430
      },
      {
        "width": 1024,
        "src": "/responsive/saas-marketing-agency-alternative-wael-aouididi-1024.webp",
        "bytes": 19802
      }
    ]
  },
  "saas-marketing-agency-alternative": {
    "width": 1536,
    "height": 1024,
    "originalBytes": 52206,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-marketing-agency-alternative-320.webp",
        "bytes": 3318
      },
      {
        "width": 640,
        "src": "/responsive/saas-marketing-agency-alternative-640.webp",
        "bytes": 9430
      },
      {
        "width": 1024,
        "src": "/responsive/saas-marketing-agency-alternative-1024.webp",
        "bytes": 19802
      }
    ]
  },
  "saas-marketing-plan-framework-founders-wael-aouididi": {
    "width": 1376,
    "height": 768,
    "originalBytes": 533148,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-marketing-plan-framework-founders-wael-aouididi-320.webp",
        "bytes": 3814
      },
      {
        "width": 640,
        "src": "/responsive/saas-marketing-plan-framework-founders-wael-aouididi-640.webp",
        "bytes": 10024
      },
      {
        "width": 1024,
        "src": "/responsive/saas-marketing-plan-framework-founders-wael-aouididi-1024.webp",
        "bytes": 17460
      }
    ]
  },
  "saas-product-video-html-demo-obs-workflow": {
    "width": 1200,
    "height": 630,
    "originalBytes": 33210,
    "variants": [
      {
        "width": 320,
        "src": "/responsive/saas-product-video-html-demo-obs-workflow-320.webp",
        "bytes": 3496
      },
      {
        "width": 640,
        "src": "/responsive/saas-product-video-html-demo-obs-workflow-640.webp",
        "bytes": 8166
      },
      {
        "width": 1024,
        "src": "/responsive/saas-product-video-html-demo-obs-workflow-1024.webp",
        "bytes": 14486
      }
    ]
  }
} as const satisfies Record<string, ResponsiveImageEntry>;
