/**
 * Phase 4A — CRO Teardown Article Data Generator
 *
 * Usage:
 *   npm run cro-teardown:generate-data -- --name <Company> --slug <slug> [options]
 *
 * Options:
 *   --name <string>        Company display name (e.g. "Hootsuite")
 *   --slug <string>        URL slug (e.g. "hootsuite")
 *   --dry-run              Run the full pipeline but do not write any files
 *   --write-content        Also write src/content/cro-teardown/articles/[slug].ts
 *
 * Examples:
 *   npm run cro-teardown:generate-data -- --name Hootsuite --slug hootsuite --dry-run
 *   npm run cro-teardown:generate-data -- --name Hootsuite --slug hootsuite
 *   npm run cro-teardown:generate-data -- --name Hootsuite --slug hootsuite --write-content
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';
import { buildEvidencePack } from './evidence-pack.js';
import { buildArticleBlueprint, type ArticleBlueprint } from './article-blueprint.js';
import type { CroTeardownPost } from '../../src/content/cro-teardown/types.js';

// ─── CLI parsing ──────────────────────────────────────────────────────────────

interface CliArgs {
  companyName: string;
  slug: string;
  dryRun: boolean;
  writeContent: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const args: Record<string, string> = {};
  const flags = new Set<string>();

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--dry-run') { flags.add('dry-run'); continue; }
    if (argv[i] === '--write-content') { flags.add('write-content'); continue; }
    if (argv[i].startsWith('--') && i + 1 < argv.length) {
      args[argv[i].slice(2)] = argv[i + 1];
      i++;
    }
  }

  if (!args.name) {
    console.error('Missing --name. Usage: npm run cro-teardown:generate-data -- --name <Company> --slug <slug>');
    process.exit(1);
  }
  if (!args.slug) {
    // Derive slug from name
    args.slug = args.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }

  return {
    companyName: args.name,
    slug: args.slug,
    dryRun: flags.has('dry-run'),
    writeContent: flags.has('write-content'),
  };
}

// ─── TypeScript file serializer ───────────────────────────────────────────────

/**
 * Serializes a value to TypeScript source syntax.
 * Uses JSON.stringify for all string leaves — this guarantees correct escaping.
 */
function serializeTs(val: unknown, depth = 0): string {
  const pad = '  '.repeat(depth);
  const padInner = '  '.repeat(depth + 1);

  if (val === null) return 'null';
  if (val === undefined) return 'undefined';
  if (typeof val === 'boolean' || typeof val === 'number') return String(val);
  if (typeof val === 'string') return JSON.stringify(val);

  if (Array.isArray(val)) {
    if (val.length === 0) return '[]';
    const items = val.map(v => `${padInner}${serializeTs(v, depth + 1)}`);
    return `[\n${items.join(',\n')},\n${pad}]`;
  }

  if (typeof val === 'object') {
    const entries = Object.entries(val as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${padInner}${k}: ${serializeTs(v, depth + 1)}`);
    if (entries.length === 0) return '{}';
    return `{\n${entries.join(',\n')},\n${pad}}`;
  }

  return 'undefined';
}

/**
 * Generates a valid TypeScript module exporting the CroTeardownPost object.
 * The output is safe to pass through tsc.
 */
function generateTsSource(slug: string, post: CroTeardownPost): string {
  const varName = slug.replace(/-([a-z])/g, (_, c: string) => (c as string).toUpperCase());
  const serialized = serializeTs(post, 0);
  return [
    `/**`,
    ` * Auto-generated by scripts/cro-teardown/generate-article-data.ts`,
    ` * Phase 4A — facts-only, no editorial interpretation.`,
    ` * Generated: ${new Date().toISOString()}`,
    ` *`,
    ` * To regenerate:`,
    ` *   npm run cro-teardown:generate-data -- --name "${post.companyName}" --slug ${slug} --write-content`,
    ` */`,
    ``,
    `import type { CroTeardownPost } from "../types";`,
    ``,
    `export const ${varName}: CroTeardownPost = ${serialized};`,
    ``,
  ].join('\n');
}

// ─── Output directory helpers ─────────────────────────────────────────────────

function saveJson(filePath: string, data: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
}

function saveText(filePath: string, text: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, text, 'utf-8');
}

// ─── Summary printer ──────────────────────────────────────────────────────────

function printSummary(blueprint: ArticleBlueprint, cli: CliArgs, outputPaths: Record<string, string>): void {
  const { post, dataQuality: q, warnings } = blueprint;
  const divider = '─'.repeat(60);

  console.log(`\n${divider}`);
  console.log(`  CRO Teardown — Phase 4A complete`);
  console.log(divider);
  console.log(`\n  Company:        ${post.companyName}`);
  console.log(`  Slug:           ${post.slug}`);
  console.log(`  Period:         ${post.fromLabel} → ${post.toLabel}`);
  console.log(`  Snapshots:      ${q.snapshotCount}`);
  console.log(`  Dry run:        ${cli.dryRun ? 'YES — no files written' : 'no'}`);

  console.log(`\n  ── Evidence quality`);
  console.log(`  Headline changed:   ${q.headlineChanged ? 'yes' : 'no'}`);
  console.log(`  Meta changed:       ${q.metaChanged ? 'yes' : 'no'}`);
  console.log(`  H2 added:           ${q.h2Added}`);
  console.log(`  H2 removed:         ${q.h2Removed}`);
  console.log(`  CTA added:          ${q.ctaAdded}`);
  console.log(`  CTA removed:        ${q.ctaRemoved}`);
  console.log(`  Nav added:          ${q.navAdded}`);
  console.log(`  Nav removed:        ${q.navRemoved}`);
  console.log(`  Visual-only diff:   ${q.visualOnly ? 'YES — no text changes detected' : 'no'}`);
  console.log(`  Mid-transition:     ${q.hasMidTransition ? 'yes' : 'no (only 2 snapshots)'}`);

  console.log(`\n  ── Generated article-data summary`);
  console.log(`  Title:            ${post.title}`);
  console.log(`  H1:               ${post.h1}`);
  console.log(`  Read time:        ${post.readTime}`);
  console.log(`  Summary cards:    ${post.summaryCards.length}`);
  console.log(`  Messaging chgs:   ${post.messagingChanges.length}`);
  console.log(`  Analysis blocks:  ${post.analysisBlocks.length}`);
  console.log(`  Lesson cards:     ${post.lessonCards.length}`);
  console.log(`  Snapshots:        ${post.snapshots.length}`);

  if (!cli.dryRun) {
    console.log(`\n  ── Output files`);
    for (const [label, p] of Object.entries(outputPaths)) {
      console.log(`  ${label.padEnd(26)} ${p}`);
    }
  }

  if (warnings.length > 0) {
    console.log(`\n  ── Warnings (${warnings.length})`);
    warnings.forEach(w => console.log(`  ⚠  ${w}`));
  }

  console.log(`\n${divider}\n`);
}

// ─── Validate that the generated post matches CroTeardownPost ─────────────────

function validatePost(post: CroTeardownPost): string[] {
  const errors: string[] = [];

  const required: (keyof CroTeardownPost)[] = [
    'slug', 'companyName', 'companyUrl', 'category', 'title', 'h1',
    'metaTitle', 'description', 'excerpt', 'author', 'authorBio',
    'datePublished', 'readTime', 'featuredImage', 'featuredImageAlt',
    'fromLabel', 'toLabel', 'snapshots', 'summaryCards', 'messagingChanges',
    'h2Added', 'h2Removed', 'ctaAdded', 'ctaRemoved', 'analysisBlocks',
    'lessonCards', 'toc', 'cta', 'relatedPosts',
  ];

  for (const key of required) {
    if (post[key] === undefined || post[key] === null || post[key] === '') {
      errors.push(`Missing required field: ${key}`);
    }
  }

  if (post.snapshots?.length === 0) errors.push('snapshots array is empty');
  if (post.summaryCards?.length === 0) errors.push('summaryCards array is empty');
  if (post.toc?.length === 0) errors.push('toc array is empty');
  if (post.relatedPosts?.length === 0) errors.push('relatedPosts array is empty');

  return errors;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const cli = parseArgs(process.argv.slice(2));
  const projectRoot = process.cwd();
  const dataDir = path.join(projectRoot, 'data', 'cro-teardowns', cli.slug);
  const writingDir = path.join(dataDir, 'writing');
  const sectionEvidenceDir = path.join(writingDir, 'section-evidence');

  console.log(`\nCRO Teardown — Phase 4A: Article data generator`);
  console.log(`Company: ${cli.companyName}  |  Slug: ${cli.slug}  |  Mode: ${cli.dryRun ? 'dry-run' : 'write'}${cli.writeContent ? ' + write-content' : ''}\n`);

  const runLog: { step: string; ok: boolean; detail?: string; ts: string }[] = [];
  const errors: string[] = [];

  const log = (step: string, ok: boolean, detail?: string) => {
    runLog.push({ step, ok, detail, ts: new Date().toISOString() });
    console.log(`  ${ok ? '✓' : '✗'} ${step}${detail ? ` — ${detail}` : ''}`);
  };

  try {
    // ── Step 1: Build evidence pack ──────────────────────────────────────────
    let pack;
    try {
      pack = await buildEvidencePack({ projectRoot, slug: cli.slug, companyName: cli.companyName });
      log('Build evidence pack', true, `${pack.snapshots.length} snapshots, diff computed`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log('Build evidence pack', false, msg);
      errors.push(msg);
      throw err;
    }

    // ── Step 2: Build article blueprint ──────────────────────────────────────
    let blueprint: ArticleBlueprint;
    try {
      blueprint = buildArticleBlueprint(pack);
      log('Build article blueprint', true,
        `${blueprint.post.analysisBlocks.length} analysis blocks, ${blueprint.post.lessonCards.length} lessons`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log('Build article blueprint', false, msg);
      errors.push(msg);
      throw err;
    }

    // ── Step 3: Validate output ───────────────────────────────────────────────
    const validationErrors = validatePost(blueprint.post);
    if (validationErrors.length > 0) {
      validationErrors.forEach(e => errors.push(e));
      log('Validate CroTeardownPost shape', false, `${validationErrors.length} field error(s)`);
    } else {
      log('Validate CroTeardownPost shape', true, 'all required fields present');
    }

    // ── Step 4: Save outputs ──────────────────────────────────────────────────
    const outputPaths: Record<string, string> = {};

    if (!cli.dryRun) {
      fs.mkdirSync(sectionEvidenceDir, { recursive: true });

      // evidence-pack.json (without full PageText to keep size reasonable)
      const packForJson = {
        slug: pack.slug,
        companyName: pack.companyName,
        companyUrl: pack.companyUrl,
        fromMonth: pack.fromMonth,
        toMonth: pack.toMonth,
        fromLabel: pack.fromLabel,
        toLabel: pack.toLabel,
        generatedAt: pack.generatedAt,
        warnings: pack.warnings,
        snapshots: pack.snapshots,
        diffSummary: {
          headlineChanges: pack.diff.headlines.length,
          metaDescChanges: pack.diff.metaDescs.length,
          titleChanges: pack.diff.titles.length,
          h2Added: pack.diff.h2Added,
          h2Removed: pack.diff.h2Removed,
          ctaAdded: pack.diff.ctaAdded,
          ctaRemoved: pack.diff.ctaRemoved,
          navAdded: pack.diff.navAdded,
          navRemoved: pack.diff.navRemoved,
          headlines: pack.diff.headlines,
          metaDescs: pack.diff.metaDescs,
          visualOnly: pack.diff.visualOnly,
        },
      };
      saveJson(path.join(writingDir, 'evidence-pack.json'), packForJson);
      outputPaths['evidence-pack.json'] = `data/cro-teardowns/${cli.slug}/writing/evidence-pack.json`;
      log('Save evidence-pack.json', true);

      // article-blueprint.json
      const blueprintForJson = {
        dataQuality: blueprint.dataQuality,
        warnings: blueprint.warnings,
        generatedAt: new Date().toISOString(),
        postSummary: {
          title: blueprint.post.title,
          h1: blueprint.post.h1,
          readTime: blueprint.post.readTime,
          summaryCardCount: blueprint.post.summaryCards.length,
          messagingChangeCount: blueprint.post.messagingChanges.length,
          analysisBlockCount: blueprint.post.analysisBlocks.length,
          lessonCardCount: blueprint.post.lessonCards.length,
          snapshotCount: blueprint.post.snapshots.length,
        },
      };
      saveJson(path.join(writingDir, 'article-blueprint.json'), blueprintForJson);
      outputPaths['article-blueprint.json'] = `data/cro-teardowns/${cli.slug}/writing/article-blueprint.json`;
      log('Save article-blueprint.json', true);

      // section-evidence/
      const ev = blueprint.sectionEvidence;
      saveJson(path.join(sectionEvidenceDir, 'summary-cards.json'), ev.summaryCards);
      saveJson(path.join(sectionEvidenceDir, 'messaging.json'), ev.messagingChanges);
      saveJson(path.join(sectionEvidenceDir, 'analysis-blocks.json'), ev.analysisBlocks);
      saveJson(path.join(sectionEvidenceDir, 'lesson-cards.json'), ev.lessonCards);
      saveJson(path.join(sectionEvidenceDir, 'h2-changes.json'), { added: ev.h2Added, removed: ev.h2Removed });
      saveJson(path.join(sectionEvidenceDir, 'cta-changes.json'), { added: ev.ctaAdded, removed: ev.ctaRemoved });
      outputPaths['section-evidence/'] = `data/cro-teardowns/${cli.slug}/writing/section-evidence/ (6 files)`;
      log('Save section-evidence/', true, '6 files');

      // generated-article-data.json — the full CroTeardownPost as JSON
      saveJson(path.join(writingDir, 'generated-article-data.json'), blueprint.post);
      outputPaths['generated-article-data.json'] = `data/cro-teardowns/${cli.slug}/writing/generated-article-data.json`;
      log('Save generated-article-data.json', true, 'full CroTeardownPost object');

      // run-log.json
      saveJson(path.join(writingDir, 'run-log.json'), runLog);
      outputPaths['run-log.json'] = `data/cro-teardowns/${cli.slug}/writing/run-log.json`;

      // errors.json
      saveJson(path.join(writingDir, 'errors.json'), { errors, count: errors.length });
      outputPaths['errors.json'] = `data/cro-teardowns/${cli.slug}/writing/errors.json`;

      // ── Step 5 (optional): Write .ts content file ─────────────────────────
      if (cli.writeContent) {
        const tsSource = generateTsSource(cli.slug, blueprint.post);
        const tsOutPath = path.join(
          projectRoot, 'src', 'content', 'cro-teardown', 'articles', `${cli.slug}.ts`,
        );
        const exists = fs.existsSync(tsOutPath);
        saveText(tsOutPath, tsSource);
        outputPaths[`articles/${cli.slug}.ts`] = `src/content/cro-teardown/articles/${cli.slug}.ts`;
        log(
          `Write src/content/cro-teardown/articles/${cli.slug}.ts`,
          true,
          exists ? 'overwritten' : 'created',
        );
      }
    } else {
      log('File writes skipped', true, 'dry-run mode');
    }

    // ── Print summary ─────────────────────────────────────────────────────────
    printSummary(blueprint, cli, outputPaths);

    if (errors.length > 0) {
      console.error(`\n${errors.length} error(s) encountered. Check data/cro-teardowns/${cli.slug}/writing/errors.json\n`);
      process.exit(1);
    }

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\nFatal error: ${msg}\n`);
    if (!cli.dryRun) {
      try {
        saveJson(path.join(writingDir, 'errors.json'), {
          errors: [msg, ...errors],
          runLog,
          count: errors.length + 1,
        });
      } catch { /* ignore secondary write failure */ }
    }
    process.exit(1);
  }
}

main();
