/**
 * Phase 4E — Selective section rerun CLI.
 *
 * Reads rerun-plan.json (generated by fix-router.ts), reruns only the
 * identified sections through the existing writer → critic → rewriter loop,
 * then reassembles the article and re-evaluates with the final judge + SEO audit.
 *
 * Usage:
 *   npm run cro-teardown:rerun-failed -- \
 *     --slug hootsuite --mode standard --max-cost 1 --max-rewrite-loops 2
 *
 * Options:
 *   --slug <string>              Teardown slug (required)
 *   --mode <string>              "standard" (default) | "flagship"
 *   --max-cost <number>          Budget cap in USD (default: 1.00)
 *   --max-rewrite-loops <n>      Max rewrite loops per rerun section (default: 2)
 *   --max-rerun-sections <n>     Cap on how many sections to rerun (default: 3)
 *   --skip-final-judge           Skip re-running the final article judge
 *   --skip-seo-audit             Skip re-running the SEO audit
 *
 * Writes:
 *   data/cro-teardowns/[slug]/writing/rerun-plan.json     (refreshed)
 *   data/cro-teardowns/[slug]/writing/final-judge.json    (updated)
 *   data/cro-teardowns/[slug]/writing/seo-audit.json      (updated)
 *   data/cro-teardowns/[slug]/writing/rerun-cost-report.json
 *   data/cro-teardowns/[slug]/writing/run-log.json        (appended)
 *   data/cro-teardowns/[slug]/writing/errors.json         (updated)
 *
 * Passing sections are never touched.
 *
 * SECURITY: ANTHROPIC_API_KEY is read exclusively from process.env or .env file.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';
import { fileURLToPath } from 'node:url';

import { CostTracker } from './llm/token-cost.js';
import { SECTION_ORDER, writeSectionLoop, type WriteSectionResult } from './section-writer.js';
import { assembleArticle } from './article-assembler.js';
import { runFinalJudge, type FinalJudgeResult } from './final-judge.js';
import { runSeoAudit, type SeoAuditResult } from './seo-auditor.js';
import { buildRerunPlan, type RerunPlan } from './fix-router.js';
import { CRITIC_PASS_SCORE } from './config/writing-config.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ExecuteRerunOpts {
  slug: string;
  writingDir: string;
  sectionsDir: string;
  plan: RerunPlan;
  mode: string;
  maxCostUsd: number;
  maxRewriteLoops: number;
  maxRerunSections: number;
  skipFinalJudge: boolean;
  skipSeoAudit: boolean;
  tracker: CostTracker;
  onLog: (section: string | null, step: string, ok: boolean, detail?: string) => void;
}

export interface ExecuteRerunResult {
  sectionsRerun: string[];
  sectionResults: WriteSectionResult[];
  finalJudgeResult: FinalJudgeResult | null;
  seoAuditResult: SeoAuditResult | null;
  errors: Array<{ section: string; error: string }>;
  /** Pre-rerun scores for comparison. */
  scoreBefore: { judge: number; seo: number };
}

// ─── Shared executor (used by both CLI and compose-all-sections.ts) ───────────

export async function executeRerunPlan(opts: ExecuteRerunOpts): Promise<ExecuteRerunResult> {
  const {
    slug, writingDir, sectionsDir, plan, mode,
    maxCostUsd, maxRewriteLoops, maxRerunSections,
    skipFinalJudge, skipSeoAudit, tracker, onLog,
  } = opts;

  const logPath = path.join(writingDir, 'run-log.json');
  const errors: Array<{ section: string; error: string }> = [];
  const sectionResults: WriteSectionResult[] = [];

  const sectionQueue = plan.sectionsToRerun.slice(0, maxRerunSections);

  const scoreBefore = {
    judge: plan.source.finalJudgeScore,
    seo:   plan.source.seoScore,
  };

  if (sectionQueue.length === 0) {
    onLog(null, 'No sections identified for rerun', true, 'rerun-plan has 0 entries');
    return {
      sectionsRerun: [],
      sectionResults: [],
      finalJudgeResult: null,
      seoAuditResult: null,
      errors: [],
      scoreBefore,
    };
  }

  const div = '─'.repeat(60);

  // ── Rerun each identified section ──────────────────────────────────────────
  for (const entry of sectionQueue) {
    const { sectionId, priority, reasons } = entry;

    // Budget guard
    if (tracker.totalCostUsd >= maxCostUsd) {
      const msg = `Budget cap $${maxCostUsd} reached before ${sectionId}. Stopping.`;
      onLog(sectionId, 'budget cap — stopped', false, msg);
      errors.push({ section: sectionId, error: msg });
      appendRunLog(logPath, { section: sectionId, step: 'budget cap — skipped', ok: false, detail: msg });
      break;
    }

    console.log(`\n${div}`);
    console.log(`  Rerunning: ${sectionId} [${priority} priority]`);
    for (const r of reasons.slice(0, 2)) {
      console.log(`    • ${r.slice(0, 100)}`);
    }
    console.log(div);

    const sectionLog = (step: string, ok: boolean, detail?: string): void => {
      const icon = ok ? '✓' : '✗';
      console.log(`  ${icon} ${step}${detail ? ` — ${detail}` : ''}`);
      appendRunLog(logPath, { section: sectionId, step, ok, detail });
    };

    try {
      // Delete existing final to force regeneration
      const finalPath = path.join(sectionsDir, `${sectionId}.final.md`);
      if (fs.existsSync(finalPath)) fs.unlinkSync(finalPath);

      const result = await writeSectionLoop({
        sectionId,
        writingDir,
        sectionsDir,
        maxRewriteLoops,
        minScore: CRITIC_PASS_SCORE,
        draftOnly: false,
        tracker,
        onLog: sectionLog,
      });

      sectionResults.push(result);

      const scoreStr = result.finalScore !== null
        ? `score ${result.finalScore}/100 — ${result.passed ? 'PASS ✓' : 'FAIL ✗'}`
        : 'draft (no score)';
      console.log(`\n  ✓ ${sectionId} rerun complete — ${scoreStr}`);

    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`\n  ✗ ${sectionId} rerun FAILED: ${msg}`);
      errors.push({ section: sectionId, error: msg });
      appendRunLog(logPath, { section: sectionId, step: 'RERUN ERROR', ok: false, detail: msg });
    }
  }

  // ── Reassemble article ─────────────────────────────────────────────────────
  console.log(`\n${div}`);
  console.log(`  Reassembling article-final.md…`);
  try {
    const assembled = assembleArticle({
      slug,
      writingDir,
      sectionsDir,
      sectionOrder: [...SECTION_ORDER],
    });
    console.log(
      `  ✓ article-final.md — ${assembled.sectionsIncluded.length} sections, ~${assembled.wordCount} words`,
    );
    if (assembled.sectionsMissing.length > 0) {
      console.log(`  ⚠ Missing: ${assembled.sectionsMissing.join(', ')}`);
    }
    appendRunLog(logPath, {
      step: 'reassemble article-final.md',
      ok: true,
      detail: `${assembled.sectionsIncluded.length} sections, ${assembled.wordCount} words`,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`  ✗ Assembly failed: ${msg}`);
    errors.push({ section: '_assembler', error: msg });
    appendRunLog(logPath, { step: 'reassemble article-final.md', ok: false, detail: msg });
  }

  // ── Re-run final judge ─────────────────────────────────────────────────────
  let finalJudgeResult: FinalJudgeResult | null = null;
  if (!skipFinalJudge) {
    try {
      finalJudgeResult = await runFinalJudge({
        slug, writingDir, mode, tracker,
        onLog: (step, ok, detail) => {
          const icon = ok ? '✓' : '✗';
          console.log(`  ${icon} ${step}${detail ? ` — ${detail}` : ''}`);
          appendRunLog(logPath, { step, ok, detail });
        },
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  ✗ Final judge failed: ${msg}`);
      errors.push({ section: '_final-judge', error: msg });
      appendRunLog(logPath, { step: 'final judge (rerun)', ok: false, detail: msg });
    }
  }

  // ── Re-run SEO audit ───────────────────────────────────────────────────────
  let seoAuditResult: SeoAuditResult | null = null;
  if (!skipSeoAudit) {
    try {
      seoAuditResult = await runSeoAudit({
        slug, writingDir, tracker,
        onLog: (step, ok, detail) => {
          const icon = ok ? '✓' : '✗';
          console.log(`  ${icon} ${step}${detail ? ` — ${detail}` : ''}`);
          appendRunLog(logPath, { step, ok, detail });
        },
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`  ✗ SEO audit failed: ${msg}`);
      errors.push({ section: '_seo-audit', error: msg });
      appendRunLog(logPath, { step: 'seo audit (rerun)', ok: false, detail: msg });
    }
  }

  return {
    sectionsRerun:    sectionResults.map(r => r.sectionId),
    sectionResults,
    finalJudgeResult,
    seoAuditResult,
    errors,
    scoreBefore,
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function saveJson(filePath: string, data: unknown): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');
}

function appendRunLog(
  logPath: string,
  entry: { section?: string; step: string; ok: boolean; detail?: string },
): void {
  let existing: unknown[] = [];
  if (fs.existsSync(logPath)) {
    try { existing = JSON.parse(fs.readFileSync(logPath, 'utf-8')) as unknown[]; } catch { /* start fresh on corrupt log */ }
  }
  existing.push({ ...entry, ts: new Date().toISOString() });
  fs.writeFileSync(logPath, JSON.stringify(existing, null, 2), 'utf-8');
}

// ─── CLI ──────────────────────────────────────────────────────────────────────

interface CliArgs {
  slug: string;
  mode: string;
  maxCostUsd: number;
  maxRewriteLoops: number;
  maxRerunSections: number;
  skipFinalJudge: boolean;
  skipSeoAudit: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const args: Record<string, string> = {};
  const flags = new Set<string>();

  for (let i = 0; i < argv.length; i++) {
    if (!argv[i].startsWith('--')) continue;
    const key = argv[i].slice(2);
    if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) {
      args[key] = argv[i + 1];
      i++;
    } else {
      flags.add(key);
    }
  }

  if (!args.slug) { console.error('Error: --slug is required'); process.exit(1); }

  return {
    slug:             args.slug,
    mode:             args.mode ?? 'standard',
    maxCostUsd:       parseFloat(args['max-cost'] ?? '1.00'),
    maxRewriteLoops:  parseInt(args['max-rewrite-loops'] ?? '2', 10),
    maxRerunSections: parseInt(args['max-rerun-sections'] ?? '3', 10),
    skipFinalJudge:   flags.has('skip-final-judge'),
    skipSeoAudit:     flags.has('skip-seo-audit'),
  };
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const cli = parseArgs(process.argv.slice(2));
  const projectRoot = process.cwd();
  const writingDir  = path.join(projectRoot, 'data', 'cro-teardowns', cli.slug, 'writing');
  const sectionsDir = path.join(writingDir, 'sections');
  const logPath     = path.join(writingDir, 'run-log.json');
  const errorsPath  = path.join(writingDir, 'errors.json');
  const costPath    = path.join(writingDir, 'rerun-cost-report.json');

  if (!fs.existsSync(writingDir)) {
    console.error(`  ✗ Writing directory not found: ${writingDir}`);
    process.exit(1);
  }

  const tracker = new CostTracker(cli.maxCostUsd);
  const div = '─'.repeat(60);

  // ── Banner ──────────────────────────────────────────────────────────────────
  console.log(`\nCRO Teardown — Phase 4E: Selective Section Rerun`);
  console.log(div);
  console.log(`  Slug              : ${cli.slug}`);
  console.log(`  Mode              : ${cli.mode}`);
  console.log(`  Budget            : $${cli.maxCostUsd}`);
  console.log(`  Max loops         : ${cli.maxRewriteLoops}`);
  console.log(`  Max rerun sections: ${cli.maxRerunSections}`);
  if (cli.skipFinalJudge) console.log(`  Judge             : skipped`);
  if (cli.skipSeoAudit)   console.log(`  SEO audit         : skipped`);
  console.log(div + '\n');

  // ── Build rerun plan ────────────────────────────────────────────────────────
  console.log(`  Building rerun plan from final-judge.json + seo-audit.json…`);
  const plan = buildRerunPlan({
    slug:        cli.slug,
    writingDir,
    maxSections: cli.maxRerunSections,
  });

  console.log(`  Sections to rerun : ${plan.sectionsToRerun.length}`);
  console.log(`  Skipped issues    : ${plan.skippedIssues.length}`);
  for (const s of plan.sectionsToRerun) {
    console.log(`    → ${s.sectionId} [${s.priority}] via ${s.source}`);
  }

  // ── Execute plan ─────────────────────────────────────────────────────────────
  const result = await executeRerunPlan({
    slug:             cli.slug,
    writingDir,
    sectionsDir,
    plan,
    mode:             cli.mode,
    maxCostUsd:       cli.maxCostUsd,
    maxRewriteLoops:  cli.maxRewriteLoops,
    maxRerunSections: cli.maxRerunSections,
    skipFinalJudge:   cli.skipFinalJudge,
    skipSeoAudit:     cli.skipSeoAudit,
    tracker,
    onLog: (section, step, ok, detail) => {
      appendRunLog(logPath, { section: section ?? undefined, step, ok, detail });
    },
  });

  // ── Persist cost + errors ─────────────────────────────────────────────────
  saveJson(costPath,   tracker.toReport(cli.slug, 'rerun'));
  saveJson(errorsPath, { errors: result.errors, count: result.errors.length });

  // ── Summary ────────────────────────────────────────────────────────────────
  const judgeAfter = result.finalJudgeResult?.overallScore ?? null;
  const seoAfter   = result.seoAuditResult?.seoScore ?? null;

  console.log(`\n${div}`);
  console.log(`  Phase 4E complete`);
  console.log(div);
  console.log(`  Sections rerun : ${result.sectionsRerun.length}`);
  if (result.sectionsRerun.length > 0) {
    for (const r of result.sectionResults) {
      const scoreStr = r.finalScore !== null
        ? `${r.finalScore}/100 — ${r.passed ? 'PASS ✓' : 'FAIL ✗'}`
        : 'n/a';
      const loops = r.loopsUsed > 0 ? ` (${r.loopsUsed} rewrite${r.loopsUsed > 1 ? 's' : ''})` : '';
      console.log(`    ${r.sectionId.padEnd(32)} ${scoreStr}${loops}`);
    }
  }

  console.log();
  const judgeBeforeStr = `${result.scoreBefore.judge}/100`;
  const judgeAfterStr  = judgeAfter !== null ? `${judgeAfter}/100` : 'skipped';
  const seoBeforeStr   = `${result.scoreBefore.seo}/100`;
  const seoAfterStr    = seoAfter !== null ? `${seoAfter}/100` : 'skipped';

  console.log(`  Final judge : ${judgeBeforeStr} → ${judgeAfterStr}`);
  console.log(`  SEO audit   : ${seoBeforeStr} → ${seoAfterStr}`);
  console.log(`  Total cost  : $${tracker.totalCostUsd.toFixed(6)}`);
  console.log(`  Errors      : ${result.errors.length}`);

  if (result.errors.length > 0) {
    for (const e of result.errors) console.log(`    ✗ [${e.section}] ${e.error}`);
  }

  console.log(`\n  rerun-plan.json      : ${path.join(writingDir, 'rerun-plan.json')}`);
  console.log(`  rerun-cost-report    : ${costPath}`);
  if (!cli.skipFinalJudge) {
    console.log(`  final-judge.json     : ${path.join(writingDir, 'final-judge.json')}`);
  }
  if (!cli.skipSeoAudit) {
    console.log(`  seo-audit.json       : ${path.join(writingDir, 'seo-audit.json')}`);
  }
  console.log(`\n${div}\n`);
}

// Only execute when run directly as a CLI (not when imported as a module).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error(`\n  ✗ Fatal: ${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
