export type SnapshotEntry = {
  month: string;
  label: string;
  screenshotPath: string;
};

export type MessagingChange = {
  element: string;
  before: string;
  after: string;
  note?: string;
};

export type AnalysisBlock = {
  id: string;
  label: string;
  period: string;
  screenshotPath: string;
  heading: string;
  annotations: string[];
};

export type LessonCard = {
  number?: string;
  title: string;
  body: string;
  tag: string;
};

export type SummaryCard = {
  label: string;
  value: string;
  note?: string;
};

export type CroTeardownPost = {
  slug: string;
  companyName: string;
  companyUrl: string;
  category: string;
  title: string;
  h1: string;
  metaTitle: string;
  description: string;
  excerpt: string;
  author: string;
  authorBio: string;
  datePublished: string;
  readTime: string;
  featuredImage: string;
  featuredImageAlt: string;
  fromLabel: string;
  toLabel: string;
  snapshots: SnapshotEntry[];
  summaryCards: SummaryCard[];
  messagingChanges: MessagingChange[];
  h2Added: string[];
  h2Removed: string[];
  ctaAdded: string[];
  ctaRemoved: string[];
  analysisBlocks: AnalysisBlock[];
  lessonCards: LessonCard[];
  paidAdsSignal?: {
    present: boolean;
    note?: string;
  };
  toc: { label: string; id: string }[];
  cta: {
    title: string;
    body: string;
    button: string;
  };
  relatedPosts: {
    label: string;
    title: string;
    description: string;
    href: string;
  }[];
  /** AI-written article body in Markdown (generated by Phase 4C). */
  articleBody?: string;
  /** 3-paragraph prose explaining why the homepage changed (generated by Phase 4C). */
  businessContext?: string;
  /**
   * Marketing-signal "At a glance" cards (generated by Phase 4C marketing-cards-generator).
   * Replaces technical summaryCards on the public page when present.
   * summaryCards is retained as internal evidence data.
   */
  marketingSummaryCards?: SummaryCard[];
  /** Internal link URLs recommended for this article (Phase 4F). */
  internalLinkSuggestions?: string[];
  /** ISO timestamp when Phase 4F published this article. */
  publishedAt?: string;
};
